### ISSUE TITLE
  Class 'CreateCardapioTable' not found 

### ISSUE THREAD

**Issue by pedrosobral** [engsoft2/univasfBuddy#9]
Reproducao do erro
- Crio banco limpo removendo as tabelas no mysql
- `php artisan migrate`
- `php artisan migrate:refresh`

![screen shot 2016-05-31 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/7574040/15688571/07567d88-2751-11e6-957e-81ff8d5c0ec5.png)

**Comment by raphaelmendes18** [comment]
Estranho... acabei de fazer aqui e foi.
![image](https://cloud.githubusercontent.com/assets/8367515/15694772/fc401b54-2776-11e6-92d1-f25f3d658073.png)

**Comment by pedrosobral** [comment]
Verdade! Instalei tudo aqui novamente, ficou blz.
